####################
#   Build Image    #
####################
FROM docker.io/ubuntu:24.04 AS builder

# Prepare environment
RUN mkdir /work
WORKDIR /work

# Define build argument to control release type
ARG PRE_RELEASE=false

# Install curl for downloading the latest release
RUN apt update &&  \
    apt install -y curl

# Detect the latest version based on the release type
# AND Download "BeamMP-Server.$CURRENT_OS.$ARCH"
# Where arch is either x86_64 or arm64
# And download to current dir as "BeamMP-Server"
COPY download-beammp-server.sh .
RUN ./download-beammp-server.sh $PRE_RELEASE

####################
#    Run Image     #
####################
FROM docker.io/ubuntu:24.04
LABEL maintainer="Rouven Himmelstein rouven@himmelstein.info"

## Game server parameter and their defaults
ENV BEAMMP_PORT "30814"
ENV BEAMMP_NAME "BeamMP New Server"
ENV BEAMMP_MAP "/levels/gridmap_v2/info.json"
ENV BEAMMP_DESCRIPTION "BeamMP Default Description"
ENV BEAMMP_MAX_CARS "1"
ENV BEAMMP_MAX_PLAYERS "10"
ENV BEAMMP_PRIVATE "true"
ENV BEAMMP_DEBUG "false"
ENV BEAMMP_AUTH_KEY ""
ENV TZ "UTC"

# Install game server required packages
RUN apt update &&  \
    apt upgrade -y && \
    apt install -y liblua5.3-0 tzdata ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/

# Create game server folder
RUN mkdir -p /beammp/Resources/Server /beammp/Resources/Client
VOLUME /beammp/Resources/Server
VOLUME /beammp/Resources/Client
WORKDIR /beammp

# Copy the previously downloaded executable
COPY --from=builder /work/BeamMP-Server ./beammp-server

# Prepare user, with uid 1000 and gid 1000
RUN chown -R 1000:1000 . &&  \
    chown -R ubuntu:ubuntu /beammp/Resources/ && \
    chmod -R 777 .
USER ubuntu

# Specify entrypoint
COPY entrypoint.sh .
ENTRYPOINT ["/beammp/entrypoint.sh"]